import { z } from "zod";
import {
  API_BASE_PATH,
  CONTRACT_VERSION,
  PROTOCOL_VERSION,
  REQUIRED_FEATURES,
  TEAM_ROUTES,
} from "./api.js";
import {
  activityItemSchema,
  actorSchema,
  catalogRecordSchema,
  changeSchema,
  collectionSchema,
  commentSchema,
  promptSchema,
  proposalSchema,
  reviewSchema,
  revisionSchema,
  tagSchema,
  tombstoneSchema,
  workspaceSchema,
} from "./entities.js";
import { ERROR_CODES, errorBodySchema, errorCodeSchema } from "./errors.js";
import { TEAM_LIMITS, teamLimitsSchema } from "./limits.js";
import { RECEIPT_RESULT_KINDS, TEAM_OPERATION_TYPES, teamOperationSchema } from "./operations.js";

/**
 * OpenAPI 3.1 and compatibility-manifest builders. The committed
 * `openapi.json` / `compatibility.json` are regenerated by
 * `scripts/generate-openapi.mjs` and verified byte-for-byte by
 * `tests/compatibility.test.ts`; never hand-edit the artifacts.
 */

/** Registry of named DTO schemas that become `#/components/schemas/*`. */
const COMPONENTS: [string, z.ZodType][] = [
  ["TeamOperation", teamOperationSchema],
  ["Actor", actorSchema],
  ["Workspace", workspaceSchema],
  ["Prompt", promptSchema],
  ["Revision", revisionSchema],
  ["Proposal", proposalSchema],
  ["Review", reviewSchema],
  ["Tag", tagSchema],
  ["Collection", collectionSchema],
  ["Comment", commentSchema],
  ["ActivityItem", activityItemSchema],
  ["CatalogRecord", catalogRecordSchema],
  ["Change", changeSchema],
  ["Tombstone", tombstoneSchema],
  ["TeamLimits", teamLimitsSchema],
  ["ErrorBody", errorBodySchema],
  ["ErrorCode", errorCodeSchema],
];

const componentIdBySchema = new Map<z.ZodType, string>(COMPONENTS.map(([id, schema]) => [schema, id]));

function componentRef(schema: z.ZodType): Record<string, unknown> {
  const id = componentIdBySchema.get(schema);
  if (id) return { $ref: `#/components/schemas/${id}` };
  return z.toJSONSchema(schema) as Record<string, unknown>;
}

const ERROR_STATUSES_BY_AUTH: Record<string, number[]> = {
  public: [426, 503],
  infrastructure: [503],
  human: [401, 426, 429, 503],
  member: [401, 403, 404, 426, 429, 503],
  contributor: [401, 403, 404, 426, 429, 503],
  maintainer: [401, 403, 404, 426, 429, 503],
  owner: [401, 403, 404, 426, 429, 503],
};

export interface CompatibilityManifest {
  protocol: number;
  contractVersion: string;
  httpMajor: string;
  features: string[];
  operations: string[];
  receiptResultKinds: string[];
  errorCodes: string[];
  routes: string[];
  limits: typeof TEAM_LIMITS;
}

export function buildCompatibilityManifest(): CompatibilityManifest {
  return {
    protocol: PROTOCOL_VERSION,
    contractVersion: CONTRACT_VERSION,
    httpMajor: API_BASE_PATH,
    features: [...REQUIRED_FEATURES],
    operations: [...TEAM_OPERATION_TYPES].sort(),
    receiptResultKinds: [...RECEIPT_RESULT_KINDS].sort(),
    errorCodes: [...ERROR_CODES].sort(),
    routes: TEAM_ROUTES.map((route) => `${route.method} ${route.path}`).sort(),
    limits: TEAM_LIMITS,
  };
}

export function buildOpenApiDocument(): Record<string, unknown> {
  const registry = z.registry<{ id: string }>();
  for (const [id, schema] of COMPONENTS) registry.add(schema, { id });
  const { schemas } = z.toJSONSchema(registry, {
    uri: (id) => `#/components/schemas/${id}`,
  }) as { schemas: Record<string, unknown> };
  // Strip the per-component $schema/$id noise the registry renderer adds.
  for (const component of Object.values(schemas)) {
    const record = component as Record<string, unknown>;
    delete record.$schema;
    delete record.$id;
  }

  const errorResponse = {
    description: "Error body per PB-TEAM-1 C2.",
    content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorBody" } } },
  };

  const paths: Record<string, Record<string, unknown>> = {};
  for (const route of TEAM_ROUTES) {
    const operation: Record<string, unknown> = {
      operationId: route.operationId,
      summary: route.summary,
      "x-auth": route.auth,
    };
    if (route.query && route.query.length > 0) {
      operation.parameters = route.query.map((param) => ({
        name: param.name,
        in: "query",
        required: param.required ?? false,
        schema: z.toJSONSchema(param.schema),
      }));
    }
    if (route.requestBody) {
      operation.requestBody = {
        required: true,
        content: { "application/json": { schema: componentRef(route.requestBody) } },
      };
    }
    const successStatuses = [route.success.status, ...(route.successAlt ?? [])];
    const responses: Record<string, unknown> = {};
    for (const status of successStatuses) {
      responses[String(status)] = {
        description: "Success.",
        content: route.success.schema
          ? {
              [route.success.contentType ?? "application/json"]: {
                schema: componentRef(route.success.schema),
              },
            }
          : undefined,
      };
    }
    for (const status of ERROR_STATUSES_BY_AUTH[route.auth] ?? []) {
      responses[String(status)] = errorResponse;
    }
    operation.responses = responses;
    paths[route.path] = { ...(paths[route.path] ?? {}), [route.method.toLowerCase()]: operation };
  }

  return {
    openapi: "3.1.0",
    info: {
      title: "PromptBranch Team API",
      version: CONTRACT_VERSION,
      description:
        "PB-TEAM-1 team workspace protocol. All paths are relative to /api/team/v1. " +
        "Responses may add fields in additive contract revisions; unknown discriminated " +
        "entity, command or event kinds must be refused by clients.",
    },
    jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
    "x-promptbranch": {
      protocol: PROTOCOL_VERSION,
      contractVersion: CONTRACT_VERSION,
      requiredFeatures: [...REQUIRED_FEATURES],
      operations: [...TEAM_OPERATION_TYPES],
      errorCodes: [...ERROR_CODES],
      limits: TEAM_LIMITS,
    },
    paths,
    components: {
      schemas,
      securitySchemes: {
        bearer: { type: "http", scheme: "bearer" },
      },
    },
  };
}
